name: Build ROCK

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build:
    uses: canonical/observability/.github/workflows/build-rock.yaml@main
    secrets: inherit
    with:
      rock-name: loki
