name: "Publish rock to GHCR:dev"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-dev:
    name: Release to GHCR
    uses: canonical/observability/.github/workflows/rock-release-dev.yaml@v2
    secrets: inherit
