name: Open a PR to OCI Factory

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release-oci-factory:
    name: Release to OCI Factory
    uses: canonical/observability/.github/workflows/rock-release-oci-factory.yaml@v2
    secrets: inherit
